---
- name: setting Develop Environment
  hosts: dev
  remote_user: vagrant
  sudo: yes
  gather_facts: no

  roles:
    - selinux
    - yum_repo
    - yum_install
    - postgresql
    - redis
    - git
    - ruby
    - clone_app
