---
- name: install postgresql
  yum: name={{ item }} state=latest
  with_items:
    - postgresql-server
    - postgresql-devel
    - postgresql-contrib
    - python-psycopg2

- name: postgresql initdb
  shell: service postgresql initdb

- name: start postgresql
  service: name=postgresql state=started  enabled=yes

- name: postgres user sudores
  lineinfile:
    dest: /etc/sudoers.d/postgres
    owner: root
    group: root
    mode: 0440
    line: "%vagrant ALL=(postgres) NOPASSWD: ALL"
    state: present
    create: yes
    validate: "visudo -cf %s"

- name : create database
  postgresql_db:
    name: "{{ postgresql.dbname }}"
    encoding: "UTF-8"
    login_user: postgres
  sudo_user: postgres
  sudo: yes

- name: create user
  postgresql_user:
    db: "{{ postgresql.dbname }}"
    name: "{{ postgresql.dbuser }}"
    password: "{{ postgresql.dbpass }}"
    priv: ALL
    state: present
    login_user: postgres
  sudo_user: postgres
  sudo: yes

- name: copy pg_hba.conf
  copy: src=pg_hba.conf dest=/var/lib/pgsql/data/pg_hba.conf owner=postgres group=postgres mode=0600
  notify:
    - restart postgresql
